In [1]:
import pandas as pd
import numpy as np 


In [2]:
data_set_ready = pd.read_csv("dataset_scaled_no_outliers.csv", sep=",")
data_set_ready

Location   MinTemp   MaxTemp  Rainfall  Evaporation  Sunshine  \
0             4  0.740056  1.609849 -0.386229     2.152373  1.130410   
1             4  0.972667  1.974703 -0.386229     1.755862  0.649802   
2             4  1.360352  2.096321 -0.386229     1.954117  1.102139   
3             4  1.717023  2.491579 -0.386229     1.888032  0.027839   
4             4  2.166738  1.746669 -0.386229     2.482798 -2.346930   
...         ...       ...       ...       ...          ...       ...   
41718         6  0.957160  1.336209 -0.386229     0.169820  0.762886   
41719         6  1.251800  1.214591 -0.386229     0.698500  0.084381   
41720         6  1.174263  1.244995 -0.386229     0.037649  0.762886   
41721         6  0.988174  1.092973 -0.386229     0.235905  0.649802   
41722         6  1.096726  1.077771 -0.386229     0.037649  0.678073   

       WindGustDir  WindGustSpeed  WindDir9am  WindDir3pm  ...  Humidity9am  \
0               11       0.870741           1          12  ...    -2.682349   
1                5       0.688044           5           6  ...    -1.343188   
2               14      -0.682191          14          15  ...    -1.647543   
3               14      -0.316795           7          14  ...    -2.743220   
4                3       0.413997           3          14  ...    -2.317123   
...            ...            ...         ...         ...  ...          ...   
41718            1      -0.316795           9           4  ...    -0.064898   
41719            0      -0.134097           9           9  ...    -0.490994   
41720            0      -0.499493           0          13  ...    -1.099704   
41721            2      -1.138936           9           6  ...    -0.125769   
41722            1      -0.773540           1           6  ...     0.543812   

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm   Temp9am  \
0        -1.851884    -1.914184    -1.771089 -0.675360  0.384390  1.302524   
1        -1.361594    -0.953537    -1.007988 -1.036260  0.761921  1.629292   
2        -1.361594    -0.889494    -1.023886 -1.036260  0.384390  1.691533   
3        -1.742930    -1.209710    -1.294151 -1.036260  0.761921  2.391750   
4        -1.525024    -1.690033    -1.294151  1.490044  1.516982  1.940499   
...            ...          ...          ...       ...       ...       ...   
41718    -0.816827    -0.697365    -0.801315 -1.397161 -1.125734  0.975756   
41719    -1.034734    -0.585289    -0.690030  1.129143 -1.503265  1.022437   
41720    -1.307117    -0.473214    -0.594642 -1.397161 -1.503265  1.022437   
41721     0.599566    -0.537257    -0.769519 -1.036260 -1.125734  1.022437   
41722    -0.816827    -0.697365    -0.928499  0.768242  0.384390  1.115799   

        Temp3pm  RainToday  RainTomorrow  
0      1.596793          0             0  
1      1.830360          0             0  
2      1.939359          0             0  
3      2.250782          0             0  
4      1.736934          0             0  
...         ...        ...           ...  
41718  1.425510          0             0  
41719  1.378797          0             0  
41720  1.394368          0             0  
41721  0.942805          0             0  
41722  1.223086          0             0  

[41723 rows x 22 columns]

In [4]:
data_set_ready.groupby("RainTomorrow").size()
class_feature = data_set_ready["RainTomorrow"].values
previous_feature = data_set_ready.drop(columns="RainTomorrow").values

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

x_treino, x_teste, y_treino, y_teste = train_test_split(previous_feature, class_feature, test_size = 0.3, random_state = 0)
# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)


In [9]:
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(x_treino, y_treino)
previsoes_naive = naive.predict(x_teste)
previsoes_naive
print(accuracy_score(y_teste, previsoes_naive))
print(confusion_matrix(y_teste, previsoes_naive))
print(classification_report(y_teste, previsoes_naive))

modelo = GaussianNB()
resultado = cross_val_score(modelo,previous_feature, class_feature, cv = kfold)
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

0.8173683790045538
[[9083 1498]
 [ 788 1148]]
              precision    recall  f1-score   support

           0       0.92      0.86      0.89     10581
           1       0.43      0.59      0.50      1936

    accuracy                           0.82     12517
   macro avg       0.68      0.73      0.69     12517
weighted avg       0.84      0.82      0.83     12517

Acurácia Média: 81.73%


In [17]:
from sklearn.svm import SVC
svm = SVC(kernel='poly', random_state=1, C = 2)
svm.fit(x_treino, y_treino)
previsoes_svm = svm.predict(x_teste)
previsoes_svm
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))
print(confusion_matrix(y_teste, previsoes_svm))
print(classification_report(y_teste, previsoes_svm))


#modelo = SVC(kernel='rbf', random_state=1, C = 2)
#resultado = cross_val_score(modelo, previous_feature, class_feature, cv = kfold)

# Usamos a média e o desvio padrão
#print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia: 87.20%
[[10477   104]
 [ 1498   438]]
              precision    recall  f1-score   support

           0       0.87      0.99      0.93     10581
           1       0.81      0.23      0.35      1936

    accuracy                           0.87     12517
   macro avg       0.84      0.61      0.64     12517
weighted avg       0.86      0.87      0.84     12517



Acurácia: 87.88% -> kernel rbf
Acurácia: 74.44% -> kernel sigmoid
Acurácia: 88.00% -> kernel linear
Acurácia: 79.52%% -> kernel linear more class_weight='balanced'

In [25]:
from sklearn.linear_model import LogisticRegression
logistica = LogisticRegression(random_state=42, max_iter=200, penalty="l2",
                               tol=0.0001, C=1,solver="lbfgs")
logistica.fit(x_treino, y_treino)
previsoes_logistica = logistica.predict(x_teste)

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_logistica) * 100.0))
print(confusion_matrix(y_teste, previsoes_logistica))
print(classification_report(y_teste, previsoes_logistica))

modelo = LogisticRegression(random_state=42, max_iter=200, penalty="l2",
                               tol=0.0001, C=1,solver="lbfgs")
resultado = cross_val_score(modelo,previous_feature, class_feature, cv = kfold)
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia: 88.09%
[[10249   332]
 [ 1159   777]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93     10581
           1       0.70      0.40      0.51      1936

    accuracy                           0.88     12517
   macro avg       0.80      0.68      0.72     12517
weighted avg       0.87      0.88      0.87     12517

Acurácia Média: 88.13%


In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p=1, weights="distance")
knn.fit(x_treino, y_treino)
previsoes_knn = knn.predict(x_teste)

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_knn) * 100.0))
print(confusion_matrix(y_teste, previsoes_knn))
print(classification_report(y_teste, previsoes_knn))

resultado = cross_val_score(knn,previous_feature, class_feature, cv = kfold)
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia: 87.14%
[[10306   275]
 [ 1335   601]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93     10581
           1       0.69      0.31      0.43      1936

    accuracy                           0.87     12517
   macro avg       0.79      0.64      0.68     12517
weighted avg       0.85      0.87      0.85     12517

Acurácia Média: 87.21%


In [36]:
from sklearn.tree import DecisionTreeClassifier

arvore = DecisionTreeClassifier(criterion='gini', random_state = 43, max_depth=6)
arvore.fit(x_treino, y_treino)
previsoes_arvore = arvore.predict(x_teste)

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_arvore) * 100.0))
print(confusion_matrix(y_teste, previsoes_arvore))
print(classification_report(y_teste, previsoes_arvore))


resultado = cross_val_score(arvore,previous_feature, class_feature, cv = kfold)
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia: 87.48%
[[10348   233]
 [ 1334   602]]
              precision    recall  f1-score   support

           0       0.89      0.98      0.93     10581
           1       0.72      0.31      0.43      1936

    accuracy                           0.87     12517
   macro avg       0.80      0.64      0.68     12517
weighted avg       0.86      0.87      0.85     12517

Acurácia Média: 87.52%


In [46]:
from sklearn.ensemble import RandomForestClassifier

random = RandomForestClassifier(n_estimators=50, criterion='gini', random_state = 42, max_depth=6)
random.fit(x_treino, y_treino)
previsoes_random = random.predict(x_teste)

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_random) * 100.0))
print(confusion_matrix(y_teste, previsoes_random))
print(classification_report(y_teste, previsoes_random))

resultado = cross_val_score(random,previous_feature, class_feature, cv = kfold)
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia: 87.65%
[[10451   130]
 [ 1416   520]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93     10581
           1       0.80      0.27      0.40      1936

    accuracy                           0.88     12517
   macro avg       0.84      0.63      0.67     12517
weighted avg       0.87      0.88      0.85     12517

Acurácia Média: 87.54%


In [65]:
from xgboost import XGBClassifier
xg = XGBClassifier(max_depth=6, learning_rate=0.005, n_estimators=300, objective='binary:logistic', random_state=3)
xg.fit(x_treino,y_treino)
previsoes_xg = xg.predict(x_teste)

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_xg) * 100.0))
print(confusion_matrix(y_teste, previsoes_xg))
print(classification_report(y_teste, previsoes_xg))

#resultado = cross_val_score(xg,previous_feature, class_feature, cv = kfold)
#print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia: 87.82%
[[10458   123]
 [ 1402   534]]
              precision    recall  f1-score   support

           0       0.88      0.99      0.93     10581
           1       0.81      0.28      0.41      1936

    accuracy                           0.88     12517
   macro avg       0.85      0.63      0.67     12517
weighted avg       0.87      0.88      0.85     12517



In [71]:
import lightgbm as lgb
dataset = lgb.Dataset(x_treino,label=y_treino)

parametros = {'num_leaves':250, # número de folhas
              'objective':'binary', # classificação Binária
              'max_depth':5,
              'learning_rate':.05,
              'max_bin':300}

lgbm=lgb.train(parametros,dataset,num_boost_round=200)

from datetime import datetime
inicio=datetime.now()
lgbm=lgb.train(parametros,dataset)
fim=datetime.now()

tempo = fim - inicio
tempo

previsoes_lgbm = lgbm.predict(x_teste)

previsoes_lgbm.shape

[LightGBM] [Info] Number of positive: 4437, number of negative: 24769
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.016825 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2393
[LightGBM] [Info] Number of data points in the train set: 29206, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.151921 -> initscore=-1.719614
[LightGBM] [Info] Start training from score -1.719614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain

(12517,)

In [72]:
for i in range(0, 12517):
    if previsoes_lgbm[i] >= .5:
       previsoes_lgbm[i] = 1
    else:
       previsoes_lgbm[i] = 0
       
       
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_lgbm) * 100.0))
print(confusion_matrix(y_teste, previsoes_lgbm))
print(classification_report(y_teste, previsoes_lgbm))

Acurácia: 88.31%
[[10324   257]
 [ 1206   730]]
              precision    recall  f1-score   support

           0       0.90      0.98      0.93     10581
           1       0.74      0.38      0.50      1936

    accuracy                           0.88     12517
   macro avg       0.82      0.68      0.72     12517
weighted avg       0.87      0.88      0.87     12517



In [75]:
from catboost import CatBoostClassifier

catboost = CatBoostClassifier(task_type='CPU', iterations=200, learning_rate=0.05, depth = 10, random_state = 5,
                              eval_metric="Accuracy")

catboost.fit( x_treino, y_treino, plot=True, eval_set=(x_teste, y_teste))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.8777306	test: 0.8740912	best: 0.8740912 (0)	total: 58.2ms	remaining: 11.6s
1:	learn: 0.8795111	test: 0.8738516	best: 0.8740912 (0)	total: 111ms	remaining: 11s
2:	learn: 0.8794768	test: 0.8755293	best: 0.8755293 (2)	total: 152ms	remaining: 9.99s
3:	learn: 0.8779018	test: 0.8751298	best: 0.8755293 (2)	total: 187ms	remaining: 9.16s
4:	learn: 0.8794083	test: 0.8757690	best: 0.8757690 (4)	total: 221ms	remaining: 8.6s
5:	learn: 0.8797165	test: 0.8764880	best: 0.8764880 (5)	total: 256ms	remaining: 8.27s
6:	learn: 0.8809149	test: 0.8769673	best: 0.8769673 (6)	total: 294ms	remaining: 8.1s
7:	learn: 0.8806067	test: 0.8766478	best: 0.8769673 (6)	total: 308ms	remaining: 7.39s
8:	learn: 0.8810176	test: 0.8769673	best: 0.8769673 (6)	total: 344ms	remaining: 7.31s
9:	learn: 0.8812915	test: 0.8772869	best: 0.8772869 (9)	total: 376ms	remaining: 7.15s
10:	learn: 0.8817709	test: 0.8765679	best: 0.8772869 (9)	total: 410ms	remaining: 7.05s
11:	learn: 0.8817366	test: 0.8766478	best: 0.8772869 (9)

In [74]:
previsoes_cat = catboost.predict(x_teste)
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_cat) * 100.0))
print(confusion_matrix(y_teste, previsoes_cat))
print(classification_report(y_teste, previsoes_cat))

Acurácia: 88.28%
[[10312   269]
 [ 1198   738]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93     10581
           1       0.73      0.38      0.50      1936

    accuracy                           0.88     12517
   macro avg       0.81      0.68      0.72     12517
weighted avg       0.87      0.88      0.87     12517

